using System.Collections.Immutable;
using Dunet;
using Loopsmith.Core.Functional;

namespace Loopsmith.Core.Domain;

/// <summary>
/// What an item of the Bungie manifest is, as Loopsmith shows it (the manifest's own item types, grouped). A weapon has
/// its slot, damage type and trait columns (the perks a roll selects; none when the excerpt doesn't say); armor its
/// slot; an armor mod the slot it only fits (none: a general mod). Nothing else has a slot.
/// </summary>
[Union]
public partial record ManifestKind
{
    partial record Subclass();
    partial record Super();
    partial record Grenade();
    partial record Melee();
    partial record ClassAbility();
    partial record Movement();
    partial record Aspect();
    partial record Fragment();
    partial record Weapon(WeaponSlot Slot, Optional<DamageType> DamageType, ImmutableArray<TraitColumn> Traits);
    partial record WeaponPerk();
    partial record Armor(ArmorSlot Slot);
    partial record ArmorMod(Optional<ArmorSlot> Slot);
    partial record ArtifactPerk();
    partial record Other();
}

/// <summary>
/// One trait column of a weapon: the perks it can roll with (the manifest's plug set; enhanced versions included), or the
/// one perk it always has (an exotic's, or a column that doesn't roll).
/// </summary>
public sealed record TraitColumn(ImmutableArray<ItemHash> Options);

/// <summary>The armor slot of an armor piece, or of a mod that only fits that piece.</summary>
public enum ArmorSlot { Helmet, Arms, Chest, Legs, ClassItem }

/// <summary>An item's rarity in the manifest: exotics are framed in gold, legendaries in purple.</summary>
public enum ItemTier { Basic, Common, Rare, Legendary, Exotic }

/// <summary>
/// One item of the manifest excerpt (<c>rules/manifest.yaml</c>, ADRs D14): its official name, what it is, its type as
/// the game words it, its rarity and its icon (a bungie.net path).
/// </summary>
public sealed record ManifestItem(
    ItemHash Hash,
    string Name,
    ManifestKind Kind,
    string Type,
    Optional<ItemTier> Tier,
    Optional<string> Icon);

/// <summary>
/// Loopsmith's excerpt of the Bungie manifest: the items the rules and the saved DIM shares name, and the damage types'
/// icons. Generated by <c>tools/manifest/extract_manifest.py</c>; empty when the rules have none.
/// </summary>
public sealed record ManifestExcerpt(
    Optional<string> Version,
    ImmutableDictionary<DamageType, string> DamageTypeIcons,
    ImmutableDictionary<ItemHash, ManifestItem> Items);
