using System.Collections.Immutable;
using Loopsmith.Core.Functional;

namespace Loopsmith.Core.Domain;

/// <summary>What an item of the Bungie manifest is, as Loopsmith shows it (the manifest's own item types, grouped).</summary>
public enum ManifestKind
{
    Subclass,
    Super,
    Grenade,
    Melee,
    ClassAbility,
    Movement,
    Aspect,
    Fragment,
    Weapon,
    WeaponPerk,
    Armor,
    ArmorMod,
    ArtifactPerk,
    Other,
}

/// <summary>The armor slot of an armor piece, or of a mod that only fits that piece.</summary>
public enum ArmorSlot { Helmet, Arms, Chest, Legs, ClassItem }

/// <summary>An item's rarity in the manifest: exotics are framed in gold, legendaries in purple.</summary>
public enum ItemTier { Basic, Common, Rare, Legendary, Exotic }

/// <summary>
/// One item of the manifest excerpt (<c>rules/manifest.yaml</c>, ADRs D14): its official name and type, its icon (a
/// bungie.net path), its rarity, and for a weapon its slot and damage type, for armor and an armor mod its armor slot
/// (none for a general mod).
/// </summary>
public sealed record ManifestItem(
    ItemHash Hash,
    string Name,
    ManifestKind Kind,
    string Type,
    Optional<ItemTier> Tier,
    Optional<WeaponSlot> WeaponSlot,
    Optional<ArmorSlot> ArmorSlot,
    Optional<DamageType> DamageType,
    Optional<string> Icon);

/// <summary>
/// Loopsmith's excerpt of the Bungie manifest: the items the rules and the saved DIM shares name, and the damage types'
/// icons. Generated by <c>tools/manifest/extract_manifest.py</c>; empty when the rules have none.
/// </summary>
public sealed record ManifestExcerpt(
    Optional<string> Version,
    ImmutableDictionary<DamageType, string> DamageTypeIcons,
    ImmutableDictionary<ItemHash, ManifestItem> Items);
